-- up
CREATE TABLE ODPE (
    id NUMBER(7) PRIMARY KEY,
    Nombre VARCHAR2(40) NOT NULL,
    Direccion VARCHAR2(100) NOT NULL,
    id_departamento NUMBER(7),
    FOREIGN KEY (id_departamento) REFERENCES Departamento(id) ON DELETE CASCADE
);

ALTER TABLE ODPE ADD (
  CONSTRAINT ODPE_pk PRIMARY KEY (id));

CREATE SEQUENCE ODPE_seq START WITH 1;

CREATE OR REPLACE TRIGGER ODPE_pk
BEFORE INSERT ON ODPE
FOR EACH ROW
BEGIN
  SELECT ODPE_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/

-- down
DROP TRIGGER ODPE_pk;
DROP SEQUENCE ODPE_seq;
DROP TABLE ODPE;